### ISSUE TITLE
Paper submission

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/JMcDM#1]
Hey guys,

JMcDM is a Julia package for Multiple-criteria decision making. It basically implements pioneer tools such as Topsis, Electre, Moora, Vikor, AHP, Dematel for multiple-criteria tools; minimax, maximin, savage, hurwicz, mle for single-criterion decision making, and a game solver for zero sum games. 

There are some tools that should/may be implemented. The package coverage will be like in the LinRegOutliers.

I plan to prepare a paper for this and plan to submit to SoftwareX journal which is indexed as Q2 type.

Would you like to participate? I would be very glad if you could come and be together.

@angeris @tantei3 @akadal

**Comment by akadal** [comment]
Hi everyone,

Thank you for this valuable invitation @jbytecode. But unfortunately, I have to work on my book project for a while. Indeed in the medium-term, I want to contribute to this repository.

Best wishes.

**Comment by jbytecode** [comment]
Here is the open invitation posted in Julia discourse:

[Open invitation for Julia package developers!](https://discourse.julialang.org/t/jmcdm-a-julia-package-for-multiple-criteria-decision-making-tools/54942)

**Comment by angeris** [comment]
Heya @jbytecode thank you so much for the invitation! (I'm honored :)

I am currently fairly busy with papers at the moment (and am likely to continue until about maybe mid March or so) so my involvement would heavily depend on what you think the timeline for the project should be! This would be a very cool project to think about, though, for sure :)

**Comment by jbytecode** [comment]
Hi @angeris ,

Thank you for the response. We haven't got a rigid deadline, but of course, there is no reason to wait if the package reaches a high coverage. If nobody comes, it takes time to complete them alone, so your joining at mid March will help to me :)
