### ISSUE TITLE
Error in Julia 1.5

### ISSUE THREAD

**Issue by jmejia8** [jbytecode/JMcDM#37]
I have some errors in Julia 1.5 about satisfying dependencies.

I think  the Julia version given in your test configuration:

https://github.com/jbytecode/JMcDM/blob/09913cbdcdb239405458bc37eeed885083a1d59b/.github/workflows/main.yml#L13

should be equal to

https://github.com/jbytecode/JMcDM/blob/417a2d6aaf8c31156c85f8b7ccecad325140cdeb/Project.toml#L15

for consistency purposes during tests.

**Comment by jbytecode** [comment]
New commit is in progress:

https://github.com/jbytecode/JMcDM/commit/ce8580f1732e746375aa643bd063648a176f3fa9

**Comment by jbytecode** [comment]
We have a problem with JuMP dependency:

https://github.com/jbytecode/JMcDM/runs/6695262868?check_suite_focus=true

What is correct compat entry for this?

**Comment by jmejia8** [comment]
JuMP v1.x needs Julia v1.6

https://github.com/jump-dev/JuMP.jl/blob/d7f3e15f33f2783e4046c3ec7bf018dca918025d/Project.toml#L29  

That could be the problem.

Maybe, JuMP v0.22.3 could be a compatible option.

**Comment by jbytecode** [comment]
It seems tests are passed in both v1.5 and v1.7:

https://github.com/jbytecode/JMcDM/runs/6695610922?check_suite_focus=true

and the new compat configuration is 

```
[compat]
DataFrames = "^1"
GLPK = ">= 0.14"
JuMP = ">= 0.22"
julia = "^1.5"
```

**Comment by jbytecode** [comment]
here is the problem 

https://github.com/JuliaRegistries/General/pull/61515#issuecomment-1144011597

**Comment by jbytecode** [comment]
after your last PR

https://github.com/JuliaRegistries/General/runs/6702824808?check_suite_focus=true

**Comment by jbytecode** [comment]
JMcDM `v0.4.2` has just been registered and it should solve the versioning problem. could you please check?

**Comment by jmejia8** [comment]
Thank you very much! Now, I can use the latest JMcDM within [Metaheuristics.jl](https://github.com/jmejia8/Metaheuristics.jl)

**Comment by jbytecode** [comment]
time to close this issue, right?

**Comment by jmejia8** [comment]
Yep. This issue has been successfully solved.
