### ISSUE TITLE
What are the core dependencies of this package? 

### ISSUE THREAD

**Issue by jmejia8** [jbytecode/JMcDM#43]
First of all, thank you for this helpful package.

I wanted to know the minimum number of dependencies required to maximize the number of MCDM techniques implemented here.

- [x] DataFrames
- [ ] GLPK
- [ ] JuMP

**Comment by jbytecode** [comment]
DataFrames is used by all of the methods, however, GLPK and JuMP have limited usability, indeed, they are required to solve game matrices and a single MCDM method.


Edit: https://github.com/jbytecode/JMcDM/search?q=JuMP

**Comment by jmejia8** [comment]
I see. Could be possible to use Requires.jl or similar stuff to reduce the installation and pre-compilation time introduced by those dependencies?

**Comment by jbytecode** [comment]
Of course, I am planning to move single criterion methods and LP based methods (in current case, it is efficiency tool - data envelop) into a different package and keep the same family of MCDM methods in `JMcDM`.

**Comment by jmejia8** [comment]
Nice! I'll keep an eye on this.

**Comment by jbytecode** [comment]
@jmejia8 - `v.0.6.0` now requires DataFrames.jl only, and if GLPK and JuMP are loaded by the user, all of the functionality is still usable. fyi. 

https://github.com/jbytecode/JMcDM/commit/8740b0b806c979863cc79afd1c97f88ea07c6b56

**Comment by jmejia8** [comment]
Thank you! I'll close this issue due to my questions have been solved.
