### ISSUE TITLE
Removing dependency of DataFrames.jl

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/JMcDM#44]
The branch `removedf` my attempt to remove the dependency of `DataFrames.jl`

https://github.com/jbytecode/JMcDM/tree/removedf

All of the methods work with a decision matrix and DataFrames serves a user-friendly representation - which is indeed not really required.

@jmejia8

**Comment by jbytecode** [comment]
the branch `removedf` is merged into the main and ready for the latest tests.

**Comment by jbytecode** [comment]
`v0.7.0` of JMcDM is out!

- Requires.jl is the single dependency.

@jmejia8

**Comment by jmejia8** [comment]
Nice! I just installed it and the precompilation stage is too fast ⚡️

Thanks for improving this useful package 📦

**Comment by jbytecode** [comment]
Integration its latest version with Metaheristics.jl requires minor changes.

**Comment by jmejia8** [comment]
>    ~Revise.jl~ Requires.jl is the single dependency.
> 

I'll update Metaheuristics.jl ASAP 🔄

**Comment by jbytecode** [comment]
Thank you! (and as you corrected, I wanted to reference Requires.jl rather than the Revise.jl which is another package I like to use in package development).
