### ISSUE TITLE
unnecessarily overloaded methods

### ISSUE THREAD

**Issue by jmejia8** [jbytecode/JMcDM#45]
This method

https://github.com/jbytecode/JMcDM/blob/b03af0cc9802cf2a2587927a022ccd73ffeda5ff/src/nds.jl#L68

is overwritten by

https://github.com/jbytecode/JMcDM/blob/b03af0cc9802cf2a2587927a022ccd73ffeda5ff/src/nds.jl#L96

causing the following warning:

> WARNING: Method definition ndsranks(Array{T, 2} where T, Array{F<:Function, 1}) where {F<:Function} in module NDS at /home/runner/.julia/packages/JMcDM/6s7Ef/src/nds.jl:68 overwritten at /home/runner/.julia/packages/JMcDM/6s7Ef/src/nds.jl:96.
>  ** incremental compilation may be fatally broken for this module **

Is this intentional?

**Comment by jbytecode** [comment]
I think the first one was accepting a dataframe. after removing this dependency, two methods conflict. The first one should be deleted

**Comment by jbytecode** [comment]
Fixed in `v0.7.2`.  Thank you for addressing this issue.

https://github.com/JuliaRegistries/General/pull/75368

**Comment by jmejia8** [comment]
Nice! Thank's
