### ISSUE TITLE
Implementation of SECA

### ISSUE THREAD

**Issue by shayandavoodii** [jbytecode/JMcDM#46]
Hi, I propose implementing the SECA method for multi-criteria decision-making. The method is based on maximizing the overall performance of alternatives with consideration of the variation information of the decision matrix within and between criteria. The technique is described in the following paper: http://dx.doi.org/10.15388/Informatica.2018.167.

SECA contains two primary steps: 1) Calculating the normalized decision matrix and 2) Solving the optimization problem.
The second step aims to find the criteria weights and evaluate the alternatives simultaneously. The optimization problem is formulated as a nonlinear quadratic programming problem. I've implemented SECA in Julia and propose it be included in the JMcDM package.
I'm looking forward to your feedback.
Regards.

**Comment by jbytecode** [comment]
Thank you for opening this issue. The SECA method looks interesting and promising as its some part is based on sub optimizations. 

How do you decide to solve the inner constrained problems?

In latest versions of JMcDM, just because it is now used by other software as a dependency, we keep the number of dependencies as small as possible. That's why we left some functionality optional depending on the resources already being installed:

```julia
@require GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6" begin
        @require JuMP = "4076af6c-e467-56ae-b986-b466b2749572" begin
            include("game.jl")
            import .Game: game, GameResult
            export GameResult
            @require DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0" begin
                include("dataenvelop.jl")
                import .DataEnvelop: dataenvelop, DataEnvelopResult
                export DataEnvelopResult
            end
        end
    end
```

Will your implementation require `Optim`, `JuMP`, and solvers? If so, we can add SECA as we implemented the other functionality based on solvers.

Thank you in advance!

**Comment by shayandavoodii** [comment]
Thank you for your response!  
> How do you decide to solve the inner constrained problems

Sorry, unfortunately, I didn't get your point here. Can you clarify? Many thanks for considering my request.
> Will your implementation require Optim, JuMP, and solvers? If so, we can add SECA as we implemented the other functionality based on solvers.

My implementation requires `JuMP`, `Statistics`, and `Ipopt` as dependencies. I tried to follow your API and the description provided [here](https://github.com/jbytecode/JMcDM/issues/3). But still, I need some help adapting the API. Can you help me with that, please?
Thank you.

**Comment by jbytecode** [comment]
Okay, I got my answers. Thank you.

- First, the link you provided is a little bit old but you can follow the current implementation of Topsis as a base as it is the cleanest one and uses many of the shared functionality: https://github.com/jbytecode/JMcDM/blob/main/src/topsis.jl
- Implementation of SAW is the very short one and it may give the idea: https://github.com/jbytecode/JMcDM/blob/main/src/saw.jl


Basically we will have a 

```julia
struct SecaMethod <: MCDMMethod end
```

and a struct that holds the results: 

```julia
struct SecaResult <: MCDMResult
    weights::Array{Float64,1}
    scores::Vector
     ....
     ranking::Array{Int64,1}
    bestIndex::Int64
end
````

Multiple dispatch for the `show()` method:

```julia
function Base.show(io::IO, result::SecaResult)
    println(io, "Scores:")
    println(io, result.scores)
    println(io, "Ordering: ")
    println(io, result.ranking)
    println(io, "Best indices:")
    println(io, result.bestIndex)
    ...
end
```

The main method:

```julia
function seca(
    decisionMat::Matrix,
    weights::Array{Float64,1},
    fns::Array{F,1},
)::SecaResult where {F<:Function}
```

and the method that takes a setting:

```julia
function seca(setting::MCDMSetting)::SecaResult
    seca(setting.df, setting.weights, setting.fns)
end
```

All of the functions and structures are hosted in the module `Seca` or `SECA` : 

```julia
module SECA

import ..MCDMMethod, ..MCDMResult, ..MCDMSetting
using ..Utilities

export seca, SecaResult, SecaMethod

using ..JuMP, ..Opopt
...
...
...

function seca(setting::MCDMSetting)::SecaResult
    seca(setting.df, setting.weights, setting.fns)
end
..
..
..

end module
```

in the file `seca.jl`. 

Is that clear?


- Do you really need to import `Statistics` package? All you need is correlations? `utilities.jl` files implements some naive versions of basic statistics, including mean and correlation.

**Comment by jbytecode** [comment]
If you provide your code, I can migrate the code into the library, or help you integrating at any point.

**Comment by shayandavoodii** [comment]
Thank you so much. Gladly, I already imitated some of the requirements of the API in the right way (You can check the source [here](https://github.com/shayandavoodii/JMcDM/commit/68b5aa06c5002f5fdf77c43041a91903bb37e061)).

Yes, this seems all clear. Still, I need to implement the `seca(setting::MCDMSetting)::SecaResult` and  `Base.show(io::IO, result::SecaResult)`.

> Do you really need to import Statistics package?

The reason behind using `Statistics` is to calculate the square matrix of correlations between each pair of criteria. Specifically, consider the following example:
```julia
julia> using Statistics

julia> rnd_mat = rand(2, 3)
2×3 Matrix{Float64}:
 0.861509  0.975015  0.897119
 0.833112  0.980883  0.766479

julia> cor(rnd_mat, dims = 1)
3×3 Matrix{Float64}:
  1.0  -1.0   1.0
 -1.0   1.0  -1.0
  1.0  -1.0   1.0
```
I know it is best to keep the dependencies low, and I will do whatever you suggest to keep maintaining the library with the most down challenge in the future.

> All you need is correlations? utilities.jl files implements some naive versions of basic statistics, including mean and correlation.

We don't need `mean` in the SECA, but the `cor`. I will check utilities.jl! Thank you.

**Comment by jbytecode** [comment]
Here is the utilities: https://github.com/jbytecode/JMcDM/blob/main/src/utilities.jl

The current version of JMcDM activates Game and DataEnvelop analysis if JuMP and GLPK are already imported. 
I will change the dependency of GLPK to IPopt. So your implementation will be migrated with zero dependency cost (Of course if we don't use Statistics.jl)

**Comment by shayandavoodii** [comment]
> We don't need `mean` in the SECA, but the `cor`. I will check utilities.jl! Thank you.

I checked and tested it; the [`cor`](https://github.com/jbytecode/JMcDM/blob/5bf9ae73c3eef1db5a5830ce3f3d7a8d236af28a/src/utilities.jl#LL44) function is excellent, and we no longer need to use `Statistics`.

> I will change the dependency of GLPK to IPopt. So your implementation will be migrated with zero dependency cost

Thank you so much! I will implement the other required functions and adaptations in the next few hours.

**Comment by jbytecode** [comment]
Great!

**Comment by shayandavoodii** [comment]
> Great!

Thanks for your support!

> and the method that takes a setting:
> ```julia
> function seca(setting::MCDMSetting)::SecaResult
>     seca(setting.df, setting.weights, setting.fns)
> end
> ```

Since SECA finds the optimal weights by itself, how should I adjust the `MCDMSetting` so it doesn't break the API? SECA even wouldn't start with initialized weights. Also, SECA needs $\beta$ [[1]](https://github.com/shayandavoodii/JMcDM/blob/68b5aa06c5002f5fdf77c43041a91903bb37e061/src/seca.jl#L25) as another input which isn't in the fields of `MCDMSetting`. What If we say `SECASettings <: MCDMSetting`? However, I think this breaks the API.

Recall:
```julia
struct MCDMSetting
    df::Matrix
    weights::Array{Float64,1}
    fns::Array{F,1} where {F<:Function}
end
```

**Comment by jbytecode** [comment]
just use 

```julia
function seca(setting::MCDMSetting)::SecaResult
    seca(setting.df, setting.fns)
end
```

**Comment by shayandavoodii** [comment]
> just use
> 
> ```julia
> function seca(setting::MCDMSetting)::SecaResult
>     seca(setting.df, setting.fns)
> end
> ```

Sure. What about the $\beta$ (I mentioned it in my previous comment)? Shall we:
```julia
function seca(setting::MCDMSetting, beta)::SecaResult
    seca(setting.df, setting.fns, beta)
end
```
?

**Comment by jbytecode** [comment]
The implementation of Vikor is a nice example for this:

```julia
struct VikorMethod <: MCDMMethod
    v::Float64
end
```

since it has some optional parameters as just like yours. So you can continue to inherit MCDMMethod.

By the way, `seca()` method can be defined as it can accept additional parameters like 

```julia
function vikor(
    decisionMat::Matrix,
    weights::Array{Float64,1},
    fns::Array{F,1};
    v::Float64 = 0.5,
)::VikorResult where {F<:Function}
```

Here is vikor: https://github.com/jbytecode/JMcDM/blob/main/src/vikor.jl

**Comment by jbytecode** [comment]
And of course, you can implement `seca(setting, beta)` as well.

**Comment by shayandavoodii** [comment]
Considering your comprehensive advice, I go for `seca(setting, beta)` because $\beta$ can considerably affect the output of SACA, so I rather keep it as a positional argument event through `seca(setting, beta)::SecaResult` beside `seca(
  decisionMat::Matrix, fns::Array{F,1}, beta::Float64; epsilon::Float64=10^-3)::SecaResult where {F<:Function}` if you're agree.

**Comment by jbytecode** [comment]
If we can't provide an automatic selection or default values for betas, we can of course add it as an positional argument as well.

**Comment by shayandavoodii** [comment]
> If we can't provide an automatic selection or default values for betas

We may not be able to do so. Although [they claim](http://dx.doi.org/10.15388/Informatica.2018.167) in their case study, the appropriate value for $\beta$ is $\beta \ge3$ (they corroborated it through testing various values for $\beta$, and they didn't propose an automatic approach for tunning $\beta$), it can differ case by case.

**Comment by jbytecode** [comment]
okay, at least we can mention this in the documentation of the library then.

**Comment by shayandavoodii** [comment]
> okay, at least we can mention this in the documentation of the library then.

Sure! Also, we can try several values of $\beta$ automatically and choose the best. However, there is a question "How many different values of $\beta$ should be tested, and in which range should we pick them?"

I think it's better to let the users handle the value of $\beta$ specifically for their use cases and input.

**Comment by shayandavoodii** [comment]
> just use
> 
> ```julia
> function seca(setting::MCDMSetting)::SecaResult
>     seca(setting.df, setting.fns)
> end
> ```

I'm almost done, but with `seca(setting::MCDMSetting, beta::Float)`. The problem is where to construct an `MCDMSetting` object, passing a vector of `weights` as its second field is mandatory, but SECA finds weights by itself. So users get confused in creating the `MCDMSetting` object.

**Comment by jbytecode** [comment]
okay let this definition omitted by now, in the future, I can modify the api as necessary.

**Comment by jbytecode** [comment]
Here is the commit for integrating SECA in JMcDM: 

https://github.com/jbytecode/JMcDM/commit/b09508a363eac8191f2668c315a02a84efb5dcb4

**Comment by jbytecode** [comment]
It seems the current form of the library passes all of the tests and seems to be stable. 

Here is the automatically generated docs: https://jbytecode.github.io/JMcDM/dev/mcdms/#SECA

I will pump the new version of `v0.7.3` in a few days. 

Thank you again for your great contribution.

**Comment by shayandavoodii** [comment]
> Here is the commit for integrating SECA in JMcDM

I'll keep an eye on it. Next time I'll come across better.

> It seems the current form of the library passes all of the tests and seems to be stable.

I'm glad to hear this and looking forward to my next contribution to your excellent library. It's been a great opportunity for collaboration.

Thank you.

**Comment by jbytecode** [comment]
The v0.7.3 of the package JMcDM has just been registered in the Julia package registry.

https://github.com/JuliaRegistries/General/pull/79412

Please feel free to close this issue if you think it is resolved.

**Comment by shayandavoodii** [comment]
> The v0.7.3 of the package JMcDM has just been registered in the Julia package registry.

Great! Happy to contribute! I'll reach you with some code refactoring of SECA and a new proposal in the coming weeks.
