### ISSUE TITLE
Implementation of TODIM

### ISSUE THREAD

**Issue by shayandavoodii** [jbytecode/JMcDM#48]
Hi
I saw you've listed TODIM as one of your TO-Dos in [README.md](https://github.com/jbytecode/JMcDM#unimplemented-methods). I'm willing to implement it. However, I have some ambiguities in some steps of it. The method has originated through this study: https://www.academia.edu/download/56873871/1991_TODIM_Basic_and_application....pdf

My ambiguities are as follows:
- [x] They claim that a score of 0-9 can be assigned to each alternative with respect to criteria. However, they should have mentioned how they chose the scores. For example, how did they figure out (or assign) a score of 1 to $i'th$ alternative in the $c'th$ criteria?
- [x] I'm confused about how did they finally find the weight of each criterion since they mentioned two approaches:
  > the scale from 1 to 9 is employed for relative comparisons between criteria. The use of this 1—9 scale relies on the latest formulation of the AHP method [17, [18](https://doi.org/10.1016/0377-2217(90)90057-I)].
  [17] Saaty T.L., Multicriteria Decision Making, The Analytic Hierarchy Process, Thomas Saaty (ed), 1988.

  And in a bit further, they mentioned:
  >  the weights of criteria are computed by averaging over the normalized columns.

  As far as I know, In the AHP, the importance of each criterion is entered by the user, and the relative importance matrix over the set of given criteria is calculated:
  ```julia
  julia> foo = [1, 2, 3]
  3-element Vector{Int64}:
  1
  2
  3
  
  # the following is the pairwise comparison of criteria
  julia> compar = foo./[foo foo foo]'
  3×3 Matrix{Float64}:
  1.0  0.5  0.333333
  2.0  1.0  0.666667
  3.0  1.5  1.0
  ```
  Afterward, the importance weights of the criteria (which tells how much each criterion will factor into the decision) are calculated using Geometric Mean:
  ```julia
  julia> imp_weights = reduce(*, compar, dims=2).^(-1/length(foo))
  3×1 Matrix{Float64}:
  1.8171205928321397
  0.9085602964160698
  0.6057068642773799
  ```
  Finally, the weight of each criterion can be calculated using the following equation:
  $W_c=\frac{imp\textunderscore weights_c}{\sum_{j=1} {imp\textunderscore weights}_j}$
  where $c$ is the $c'th$ criterion, $imp\textunderscore weights_c$ is the importance weights of the $c'th$ criterion
  ```julia
  julia> weights = imp_weights./sum(imp_weights)
  3×1 Matrix{Float64}:
  0.5454545454545454
  0.2727272727272727
  0.1818181818181818
  ```
  But in this process, we do not have an operation like *"**averaging over** normalized weights"*. So a clarification about whether they achieved the weight of criteria using the same approach in the AHP is needed.
- [x] The last ambiguity is where they used a parameter named $a_{rc}$ in determining the dominance of the $i'th$ alternative over the $j'th$ alternative:
  $\delta_{(i, j)}=\sum [a_{rc}(w_{ic} - w_{jc})]$
   They didn't mention what's $a$ in the above (or maybe I haven't grasped it). But I guess it should be the relative importance of the reference criterion over the $c'th$ criterion.

**Comment by jbytecode** [comment]
of course, thank you for your contributions!

Let's start from the top of the issues: 

```
They claim that a score of 0-9 can be assigned to each alternative with respect to criteria. However, they should have mentioned how they chose the scores. For example, how did they figure out (or assign) a score of 1 to 
 alternative in the 
 criteria?
```

I think scoring is subjective and depends to the researcher, right?

**Comment by shayandavoodii** [comment]
> of course, thank you, you're welcome!
> 
> Let's start from the top of the issues:
> 
> ```
> They claim that a score of 0-9 can be assigned to each alternative with respect to criteria. However, they should have mentioned how they chose the scores. For example, how did they figure out (or assign) a score of 1 to 
>  alternative in the 
>  criteria?
> ```
> 
> I think scoring is subjective and depends to the researcher, right?

Thanks! Okay. So, one approach can be how [(Alali & Tolga, 2019)](https://doi.org/10.1016/j.eswa.2019.01.054) treated in assigning the initial relative scores of each alternative. They proposed to bin each element into ten bins:
> A score of 10 is assigned to the equities [alternatives] that are in top 10% for the related criteria. In contrast, equities [alternatives] with the highest correlation are assigned 1.

This means If $c'th$ criteria is indigenously positive, then the more the value of the alternative in the criteria, the more important the alternative, and vice versa.
If $c'th$ criteria is indigenously negative, the more the value of the alternative in the criteria, the less important, and vice versa.

**Example**  
Let us say `criterion_1` is inherently positive criteria and is a vector that each value in it corresponds to the related alternative. It includes values from 1. up to 10. :
```julia
julia> criterion_1 = rand(1.:10., 20);
```
Then, ten bins for values in the range of `1.:10.` should be considered. 
```julia
julia> using CategoricalArrays

julia> bins = cut(1.:10., 10)
10-element CategoricalArray{String,1,UInt32}:
 "Q1: [1.0, 1.9)"
 "Q2: [1.9, 2.8)"
 "Q3: [2.8, 3.7)"
 "Q4: [3.7, 4.6)"
 "Q5: [4.6, 5.5)"
 "Q6: [5.5, 6.4)"
 "Q7: [6.4, 7.3)"
 "Q8: [7.3, 8.2)"
 "Q9: [8.2, 9.1)"
 "Q10: [9.1, 10.0]"
```
Now, if the `criterion_1[1]` is in the tenth quantile, its score is 10. This was just an example to show the idea behind binning alternatives. The point is where in this approach, the extreme values of `criterion_1` should be considered in creating the quantiles.

Another example:
A naive implementation can be:
```julia
julia> criterion_1 = rand(1.:17.8, 20);

julia> b = minimum(criterion_1):maximum(criterion_1)/10:maximum(criterion_1)
1.0:1.7:16.3

julia> bins = [(b[i],b[i+1]) for i∈eachindex(b) if i!=lastindex(b)]
9-element Vector{Tuple{Float64, Float64}}:
 (1.0, 2.7)
 (2.7, 4.4)
 (4.4, 6.1)
 (6.1, 7.8)
 (7.8, 9.5)
 (9.5, 11.2)
 (11.2, 12.9)
 (12.9, 14.6)
 (14.6, 16.3)

julia> idx_quantile = []
Any[]

julia> for item∈criterion_1
         for bin∈bins
           if bin[1]<=item<bin[2]
             println(item, "∈", bin)
             push!(idx_quantile, findfirst(==(bin), bins))
             break
           end
         end
       end
5.0∈(4.2, 5.8)
13.0∈(12.2, 13.8)
15.0∈(13.8, 15.4)
11.0∈(10.6, 12.2)
6.0∈(5.8, 7.4)
3.0∈(2.6, 4.2)
3.0∈(2.6, 4.2)
13.0∈(12.2, 13.8)
1.0∈(1.0, 2.6)
7.0∈(5.8, 7.4)
11.0∈(10.6, 12.2)
13.0∈(12.2, 13.8)
12.0∈(10.6, 12.2)
12.0∈(10.6, 12.2)
14.0∈(13.8, 15.4)
8.0∈(7.4, 9.0)

julia> idx_quantile
16-element Vector{Any}:
 3
 8
 9
 7
 4
 2
 2
 8
 1
 4
 7
 8
 7
 7
 9
 5
```
This means the first alternative in the `criterion_1` has a score of 3, the second alternative has a score of 8, and so on. Note that the reason behind the existing 9 bins rather than 10 is that I wrote `maximum(criterion_1)/10` in defining `b`. By replacing `10` with `11`, we will have 10 bins.

**Comment by jbytecode** [comment]
what a nice progress and documentation! thank you for your effort. I look forward to your implementation.

**Comment by shayandavoodii** [comment]
Thank you. It was related to my first ambiguity. I can tackle it with the specified approach and some code refactoring. However, the last two ambiguities remained vague to me still.

**Comment by shayandavoodii** [comment]
Hey, sorry for the long break. I want to finish this assignment and get the job done. I need help at this point.
Assume I have a criterion and I want to assign a score of 10 to an alternative if its value is among the top 10% of the series and give a score of 9 if its value is among the top [80% 90%) values of the series and so on. I've implemented this, but I'm not sure if the concept behind my implementation is aligned with what it should be. How can I ensure?

```julia
function AMatConstructor(decisionMat::Matrix, fns::Array{F,1})::Matrix where {F<:Function}
    size(decisionMat, 2) == length(fns) || DimensionMismatch("The number of functions must
    be equal to the number of columns of decision matrix.") |> throw
    all(func -> func ∈ (maximum, minimum), fns) || ArgumentError("The functions must be either
    maximum or minimum.") |> throw

    n, m = size(decisionMat)
    A = zeros(n, m)
    for j in 1:m

        vals = decisionMat[:,j]
        if fns[j] == minimum
            for i in 1:n
                A[i,j] = sum(vals .>= decisionMat[i,j]) / n * 10 |> round
            end
        else
            for i in 1:n
                A[i,j] = sum(vals .<= decisionMat[i,j]) / n * 10 |> round
            end
        end
    end
    return A
end
```
Inputs:
```julia
mat = [
           1.0     0.9925;
           0.8696  0.8271;
           0.7391  0.8684;
           0.5217  0.7895;
           0.6522  0.9135;
           0.6087  0.8346;
           0.913   0.185 ;
           0.8696  0.9624;
           0.8261  1.0   ;
           0.3478  0.8195
       ];
fns = [maximum, minimum];
A = AMatConstructor(mat, fns)
```
gives:
```
10×2 Matrix{Float64}:
 10.0   2.0
  8.0   7.0
  5.0   5.0
  2.0   9.0
  4.0   4.0
  3.0   6.0
  9.0  10.0
  8.0   3.0
  6.0   1.0
  1.0   8.0
```

**Comment by jbytecode** [comment]
How about using `quantile() `for this?

```julia
range1 = quantile(data, 0.80)
range2 = quantile(data, 0.90)
if range1 < value < range2 
    dosomething...
end 
```

**Comment by shayandavoodii** [comment]
I will check your proposal, this is a good practice to know if my proposed procedure is working right.

**Comment by jbytecode** [comment]
`quantile(x, 0.20)` will report a special value which means 'what is the number that divides the values by %0.20 on the left and %0.80 on the right when it is sorted in ascending order' and probably it is what you mentioned above.

**Comment by shayandavoodii** [comment]
> `quantile(x, 0.20)` will report a special value which means 'what is the number that divides the values by %0.20 on the left and %0.80 on the right when it is sorted in ascending order' and probably it is what you mentioned above.

So this may not be what we need 🤔.  We need to i.e., find the values that are between %10 and %20 of sorted values. I should test whether we can use the `quantile` to find the right boundaries.

A while ago I provided an example:
https://github.com/jbytecode/JMcDM/issues/48#issuecomment-1466836343

**Comment by jbytecode** [comment]
Do we have a reference example with a provided set of inputs and the output? It's better to implement whole the algorithm and finally test if it produces the expected output.

**Comment by shayandavoodii** [comment]
No, we don't have a specific example, unfortunately.

**Comment by jbytecode** [comment]
okay, if we don't have a specific reference example, it is a better second chance to create a decision matrix in which the best option dominates all others, the second best option dominates the remaining (n-2) options, and the third best option dominates the remaining (n-3), and so on so forth.

**Comment by jbytecode** [comment]
for example

|    Alternative  |   Crit 1   | Crit 2  |  Crit 3   |
| :-------------:     | :--------:    | :------:  | :------:    |
|  Alt 1              |     10       |    11     |   12      |
| Alt 2                |   7          |    8       |    9       |
| Alt 3                |  4           |    5       |    6       |
|  Alt 4               |  1          |      2      |    3       |


with Crit 1, Crit 2, and Crit 3 are subject to maximization and weights are 1/3 for all single criteria is a good playground test sandbox.

**Comment by jbytecode** [comment]
with using this test case, we can test at least the quality of ordering of the method, however, we can't really be sure of the scores calculated.

**Comment by shayandavoodii** [comment]
The scoring procedure can be tested somewhat through the example.
I'll take care of it and report the result. However, I should tackle the unit test error in the first place. I'll find a way for further tests on the scoring issue.

**Comment by shayandavoodii** [comment]
So, here is the result:

```julia
julia> decisionMat = [
       10 11 12
       7 8 9
       4 5 6
       1 2 3
       ]

julia> fns = [maximum, maximum, maximum]

julia> weights = fill(1/3, 3)

julia> result = todim(decisionMat, weights, fns)
Scores:
[1.0, 0.75, 0.375, 0.0]
Ordering:
[1, 2, 3, 4]
Best indice:
1
```
