### ISSUE TITLE
TODIM's Docstring adjustment

### ISSUE THREAD

**Issue by shayandavoodii** [jbytecode/JMcDM#58]
This part of the docstring should be adjusted. Would you mind changing it or I can open another PR to fix it?
https://github.com/jbytecode/JMcDM/blob/4381966f2b7b46024714c141fad6dfde88fed585/src/todim.jl#L223C1-L228C2

It should be replaced with:
```
TODIMResult([1.0 0.9925; 0.8696 0.8271; … ; 0.6087 0.8346; 0.913 0.185], [2.0, 3.0], [1.0, 0.4285714285714285, 0.5952380952380951, 0.0, 0.5714285714285714, 0.30952380952380953, 0.3095238095238094], [1, 3, 5, 2, 6, 7, 4], 1)
```

**Comment by jbytecode** [comment]
please send a PR
