### ISSUE TITLE
JMcDM compilation fails 

### ISSUE THREAD

**Issue by NiharikaPatel** [jbytecode/JMcDM#60]
Hello, 

JMcDM no longer compiles on my machine and Im getting the following error. I'm assuming it has something to do with the docstrings recently added .
![image](https://github.com/jbytecode/JMcDM/assets/31861212/7adfdabb-441e-493a-9e1a-a9f40d307ee0)

**Comment by jbytecode** [comment]
It's interesting that the package compiles on both Windows, Linux, and MacOS as seen in GitHub actions.

The file `todim.jl` has a docstring with a special character `×` in `7×2 Matrix{Float64}:`. Do you think that is the reason?

**Comment by jbytecode** [comment]
@shayandavoodii - What do you think?

**Comment by NiharikaPatel** [comment]
I'm on a Ubuntu 20 system if that helps.

**Comment by NiharikaPatel** [comment]
For now I reverted to using version 0.7.11 and that compiles fine for me.

**Comment by jbytecode** [comment]
could you please remove the docstring of todim and try to compile again?

**Comment by NiharikaPatel** [comment]
I'm actually using the package through a dependency of Metaheuristics so I would have fork the repo to make those changes. But this is what I found if that's helpful 
![image](https://github.com/jbytecode/JMcDM/assets/31861212/49f114ed-ae9a-4493-831d-23322759f9a1)

**Comment by jbytecode** [comment]
yes, it seems the docstring includes some illegal characters that Julia doesn't want to handle. I am sending a commit now and waiting it to pass the tests.

**Comment by NiharikaPatel** [comment]
Okay, thank you for the quick response . We appreciate it!

**Comment by jbytecode** [comment]
I've just pumped the release `v0.7.13`. The docstring is cleaned of special characters including the cross and backslash.

Here is the process: https://github.com/JuliaRegistries/General/pull/99192

After 5 or 10 minutes, I think it gets ready!

**Comment by jbytecode** [comment]
will it possible to try it out when it is available at the global Julia registry?

**Comment by NiharikaPatel** [comment]
Give me sometime, I'm going to try and see if it works with all my other dependencies as this actually came up while we tried to add a few more other packages. I can check if it works on global julia after that. In principle it should !

**Comment by jbytecode** [comment]
`v0.7.13` is out.

**Comment by NiharikaPatel** [comment]
It compiles for me as a dependency at least using version 0.7.13. Thanks for the fix!

**Comment by shayandavoodii** [comment]
> @shayandavoodii - What do you think?

Hi, Sorry I have just been online.

> JMcDM no longer compiles on my machine and Im getting the following error. I'm assuming it has something to do with the docstrings recently added .

This is weird.

Regarding the `/` and `×` characters (see [[1](https://github.com/jbytecode/JMcDM/commit/6fa590b69ba02c917ce25503e51d3e2ca55bc620#diff-ffb194db28d692815e58477f827d8f84e83392a921b8a7e354ae435231c969d8L21)] and [[2](https://github.com/jbytecode/JMcDM/commit/6fa590b69ba02c917ce25503e51d3e2ca55bc620#diff-ffb194db28d692815e58477f827d8f84e83392a921b8a7e354ae435231c969d8L51)], respectively), I used the same chars in my package and everything is ok (see [[1](https://github.com/shayandavoodii/OnlinePortfolioSelection.jl/blob/main/src/Algos/TPPT.jl#L4)] and [[2](https://github.com/shayandavoodii/OnlinePortfolioSelection.jl/blob/main/src/Algos/TPPT.jl#L100)], respectively).
Therefore, I wonder how that happened for @NiharikaPatel. 🤔

@NiharikaPatel, Could you please mention the version of Julia you were using in this case?

**Comment by NiharikaPatel** [comment]
Hey  @shayandavoodii yes, maybe it is the version. We are still at LTS 1.6.7.

**Comment by shayandavoodii** [comment]
> maybe it is the version

That's the version for sure. You wouldn't have that problem on Julia `v1.8`+.
