### ISSUE TITLE
Question about AHP module

### ISSUE THREAD

**Issue by queueyong** [jbytecode/JMcDM#62]
Hi, I am trying to apply AHP for my decision making problem. But it doesn't seem to work properly. 

By looking at the implementation, the function "ahp()" seems to receive Vector-type as its first argument, but in the example code it seems not. Am I doing something wrong?
 - function ahp(comparisonMatrixList::Vector, criteriaComparisonMatrix::Matrix)::AHPResult

Thank you for your effort.

(below is a short sample data that I am trying to apply AHP)

using JMcDM

mat_criteria = [1 5 2 3; 1/5 1 1/4 1/2; 1/2 4 1 2; 1/3 2 1/2 1]
mat_alt_by_c1 = [1 1/3 1/6; 3 1 1/3; 6 3 1]
mat_alt_by_c2 = [1 2 4; 1/2 1 2; 1/4 1/2 1]
mat_alt_by_c3 = [1 2 5; 1/2 1 2; 1/5 1/2 1]
mat_alt_by_c4 = [1 1/2 1/5; 2 1 1/3; 5 3 1]

aug_mat = hcat(mat_alt_by_c1, mat_alt_by_c2, mat_alt_by_c3, mat_alt_by_c4)

result = ahp(aug_mat, mat_criteria)

![화면 캡처 2024-09-02 211145](https://github.com/user-attachments/assets/5e06ea4d-94c1-4463-aa5e-ef5ed27e371c)

**Comment by jbytecode** [comment]
How about doing 

```julia
aug_mat = [mat_alt_by_c1, mat_alt_by_c2, mat_alt_by_c3, mat_alt_by_c4]
```

instead of 

```julia
aug_mat = hcat(mat_alt_by_c1, mat_alt_by_c2, mat_alt_by_c3, mat_alt_by_c4)
```

**Comment by jbytecode** [comment]
btw, it's type `comparisonMatrixList::Vector` hiddens the underlying type of `comparisonMatrixList::Vector{Matrix{Float64}}`, so will fix it in the next release.

**Comment by jbytecode** [comment]
https://github.com/jbytecode/JMcDM/commit/b52cbd6dde2935da342c27d05d9feca30c7a8098

**Comment by jbytecode** [comment]
and here is the updated documentation:

https://jbytecode.github.io/JMcDM/dev/mcdms/#AHP

**Comment by queueyong** [comment]
Appreciate for your quick response and action. It works really well! Many thanks :)

**Comment by jbytecode** [comment]
Thank you for your interest in the package.
